server:
  port: 9999
spring:
  application:
    name: config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      spring:
        config:
          import: "optional:config-server:"
        cloud:
          config:
            enabled: true
            discovery:
              enabled: true
