server:
  port: 4444

spring:
  application:
    name: config-server
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: C:/Users/conf

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka